# Generated by Django 5.0.6 on 2024-07-03 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PsychologistProfile',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.userprofile')),
                ('average_rating', models.DecimalField(decimal_places=2, default=1, max_digits=3)),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_images/')),
                ('description', models.TextField()),
            ],
            bases=('users.userprofile',),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, default=1, max_digits=3)),
                ('comment', models.CharField(max_length=750)),
                ('last_updated', models.DateField(auto_now=True)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='users.userprofile')),
                ('psycho_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to='users.psychologistprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user_from', 'psycho_to'), name='unique_rating_given_user_and_psy'),
        ),
    ]
