# Generated by Django 5.0.6 on 2024-07-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologistprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True),
        ),
    ]
